version: '3.9'
services:
  app:
    container_name: megumi-coquette
    image: ghcr.io/ighorpi/megumi-coquette-bot
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    # - "3000:3000"
    environment:
      NODE_ENV: production
      DISCORD_TOKEN: '${DISCORD_TOKEN}'
      DISCORD_DEVELOPMENT_GUILD_ID: '${DISCORD_DEVELOPMENT_GUILD_ID}'
      DATABASE_URL: '${DATABASE_URL}'

    networks:
      - gojo-pharaoh-network
networks:
  gojo-pharaoh-network:
    driver: bridge
